### ISSUE TITLE
[BUG] go build fails at elrond-go/cmd/node crypto/ecdsa 

### ISSUE THREAD

**Issue by BlockchainRevolutionOnline** [ElrondNetwork/elrond-go#1890]
$ cd ~/go/src/github.com/ElrondNetwork/elrond-go/cmd/node
$ go build 
# crypto/ecdsa
/usr/local/go/src/crypto/ecdsa/ecdsa_noasm.go:16:14: undefined: signGeneric
/usr/local/go/src/crypto/ecdsa/ecdsa_noasm.go:21:9: undefined: verifyGeneric

node does not compile

<details>
<summary>Building of "node" binary fails</summary>
<pre>
Application version string: v1.0.127/go1.13.5/linux-amd64 -->
Hosting VPS: Ubuntu 18.04 on VMware and Ubuntu 20.04 at active-servers.com --> 
</pre>
</details>

**Comment by AdoAdoAdo** [comment]
this seems like there is a problem with your installation of go.
the reported errors are in go library files.

could you do a clean install of go on your machine and try again?
first completely remove the `/usr/local/go` folder

**Comment by BlockchainRevolutionOnline** [comment]
Clean install of go solved the issue. Thanks!

**Comment by joesixpack** [comment]
Just ran into this after updating my existing Go from 1.13 to 1.13.5 USING THE FUNCTION PROVIDED IN FUNCTIONS.CFG (!!!)

**Comment by joesixpack** [comment]
The problem with removing /usr/local/go if that qualifies as a "clean install" since I see no Debian installation package at GoLang, is if the script detects a different version of Go (such as 1.14.4) at an alternative path, it will not install 1.13.5.

**Comment by valentin-lup** [comment]
Unfortunately the scripts only check for the availability of the go binary... I cannot remove/re-install go because of the many different ways in which an existing binary could have been installed.
